#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2018, Joyent, Inc.
#

#
# "mockcloud-setup" service for setting up a mockcloud zone on first boot
# after (re)provision.
#

set -o xtrace

. /lib/svc/share/smf_include.sh

echo "hi from mockcloud-setup"

exit $SMF_EXIT_OK
