#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2015, Joyent, Inc.
#

#
# Rsync the master in this working copy to the install on the given HN.
#

set -o xtrace
set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE="root@$1"

if [[ -z "$MOCKCLOUD_ZONE" ]]; then
    MOCKCLOUD_ZONE=$(ssh $NODE "vmadm lookup -1 alias=mockcloud0" 2>/dev/null)
fi
echo "MOCKCLOUD_ZONE: $MOCKCLOUD_ZONE"

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
else
    # Clean node_modules everytime.
    ssh $NODE rm -rf /zones/$MOCKCLOUD_ZONE/root/opt/smartdc/mockcloud/node_modules
fi

rsync -av ${TOP}/ \
    $NODE:/zones/$MOCKCLOUD_ZONE/root/opt/smartdc/mockcloud/ \
    $extraOpts \
    --exclude .git/ \
    --exclude /config.json \
    --exclude /deps/ \
    --exclude /doc/ \
    --exclude /smf/ \
    --exclude /tools/ \
    --exclude /tmp/ \

state=$(ssh ${NODE} svcs -z ${MOCKCLOUD_ZONE} -H -o state mock-agent)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm -z ${MOCKCLOUD_ZONE} clear mock-agent
else
    ssh ${NODE} svcadm -z ${MOCKCLOUD_ZONE} restart mock-agent
    ssh ${NODE} svcadm -z ${MOCKCLOUD_ZONE} enable mock-agent
fi
